upload-doc = false
tag-prefix = ""
pre-release-commit-message = "[tdiag] Release version {{version}}"
pro-release-commit-message = "[tdiag] Development version {{next_version}}"
tag-message = "version {{version}}"
dev-version-ext = "pre"
